services:

  task-management-db:
    image: postgres:17.6
    container_name: task-management-db
    environment:
      POSTGRES_DB: task-management-system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - task-management-db-data:/var/lib/postgresql/data
    ports:
      - "5438:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d task-management-system" ]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  java-server:
    build:
      dockerfile: Dockerfile
      target: dev
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://task-management-db:5432/task-management-system
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    env_file:
      - .env
    volumes:
      - maven-cache:/root/.m2
    ports:
      - "8091:8090"
    depends_on:
      task-management-db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8090/api/v1/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 500s
    restart: on-failure

volumes:
  task-management-db-data:
  maven-cache:
