server.port=${SERVER_PORT}
server.servlet.context-path=${SERVER_CONTEXT_PATH}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jackson.deserialization.fail-on-unknown-properties=true
jwt.expiration=${JWT_EXPIRATION}
jwt.refresh.expiration=${JWT_REFRESH_EXPIRATION}
jwt.secret=${JWT_SECRET}
jwt.issuer=${JWT_ISSUER}
jwt.audience=${JWT_AUDIENCE}
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
