server.port=${SERVER_PORT:8090}
server.servlet.context-path=${SERVER_CONTEXT_PATH:/api}
spring.datasource.url=${DB_URL:jdbc:postgresql://task-management-db:5432/task-management-system}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jackson.deserialization.fail-on-unknown-properties=true
jwt.expiration=${JWT_EXPIRATION:900000}
jwt.refresh.expiration=${JWT_REFRESH_EXPIRATION:3000000}
jwt.secret=${JWT_SECRET:jwt-secret-here}
jwt.issuer=${JWT_ISSUER:jwt-issuer-here}
jwt.audience=${JWT_AUDIENCE:jwt-audience-here}
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
dropbox.access-token=${DROPBOX_ACCESS_TOKEN:access-token-here}
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
google.client.id=${GOOGLE_CLIENT_ID:google-client-id-here}
google.client.secret=${GOOGLE_CLIENT_SECRET:google-client-secret-here}
google.redirect.uri=${GOOGLE_REDIRECT_URI:google-redirect-url-here}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:mail-username}
spring.mail.password=${MAIL_PASSWORD:mail-password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
whatsapp.api.token=${META_ACCESS_TOKEN:meta-access-token-here}
whatsapp.api.phone-number-id=${PHONE_NUMBER_ID:12345678}
whatsapp.api.url=https://graph.facebook.com/v25.0
